#!/bin/bash

set -e -u

WIMLIB_ARCH=i686
if [ $# -ge 1 ]; then
	WIMLIB_ARCH=$1
fi

if [[ $WIMLIB_ARCH = i686 ]] ; then
	DESTDIR=/mnt/tmp/wimlib
elif [[ $WIMLIB_ARCH = x86_64 ]]; then
	DESTDIR=/mnt/tmp/x64/wimlib
else
	echo "Unknown architecture $1" 1>&2
	exit 2
fi

VERSION=$(grep 'This is wimlib version' README | grep -o '[0-9]\+\.[0-9]\+\.[0-9]')
ZIPFILE=wimlib-${VERSION}-windows-${WIMLIB_ARCH}-bin.zip

if ! grep -q "./configure --host=${WIMLIB_ARCH}-w64-mingw32" config.log; then
	./configure --host=${WIMLIB_ARCH}-w64-mingw32
fi

make -j2

rm -f $DESTDIR/{libwim-*.dll,doc/*,README*,NEWS*,wim*.bat}

cp .libs/imagex.exe $DESTDIR/wimlib-imagex.exe
cp .libs/libwim-*.dll $DESTDIR
cp README* NEWS $DESTDIR

for fil in ./doc/wimlib-imagex-*.1; do
	base=`basename $fil`
	base=${base%%.1}
	cmd=$(echo $base | sed s/wimlib-imagex-//)
	if [ $cmd == mount -o $cmd == mountrw -o $cmd == unmount ]; then
		continue
	fi

	echo $fil
	#MANWIDTH=80 man $fil | col -b > $DESTDIR/doc/$base
	man -t $fil | ps2pdf - $DESTDIR/doc/${base}.pdf
	sed 's/$/\r/g' > $DESTDIR/wim${cmd}.bat <<- EOF
		@echo off
		%~dp0\\wimlib-imagex $cmd %*
	EOF
done

#for fil in $DESTDIR/{README*,NEWS} $DESTDIR/doc/*; do
for fil in $DESTDIR/{README*,NEWS}; do
	sed < $fil > ${fil}.txt -e 's/$/\r/g'
	rm $fil
done


rm -f $ZIPFILE
(
	dir=$PWD
	cd $(dirname $DESTDIR) &> /dev/null
	zip -r $dir/$ZIPFILE $(basename $DESTDIR)
)
