.TH WIMLIB-IMAGEX "1" "March 2016" "wimlib 1.9.1" "User Commands"
.SH NAME
wimlib-imagex-join \- Join split WIMs into a standalone one-part WIM
.SH SYNOPSIS
\fBwimlib-imagex join\fR [\fIOPTION\fR...] \fIOUT_WIMFILE\fR
\fISPLIT_WIM_PART\fR...
.SH DESCRIPTION
Joins the \fISPLIT_WIM_PARTs\fR into a standalone one-part WIM \fIOUT_WIMFILE\fR.
This command is also available as simply \fBwimjoin\fR if the appropriate hard
link or batch file has been installed.
.PP
All parts of the split WIM  must be specified.  You probably want to do so using
a shell wildcard.
.PP
\fBwimlib-imagex join\fR can join both non-pipable and pipable split WIMs.
.SH OPTIONS
.TP 6
\fB--check\fR
When reading each \fISPLIT_WIM_PART\fR, verify its integrity if the integrity table
is present; additionally, when writing \fIOUT_WIMFILE\fR, write an integrity
table.  If this option is not specified, an integrity table will be included in
\fIOUT_WIMFILE\fR if and only if one was present in the first part of the split
WIM.
.SH EXAMPLES
Join a split WIM, with the parts named `windows*.swm' where the * is anything
(usually the number of the part, except for the first part which may have no
number), and write the joined WIM to the file `windows.wim'.
.RS
.PP
wimlib-imagex join windows.wim windows*.swm
.RE
.SH NOTES
\fBwimlib-imagex join\fR is roughly equivalent to:
.RS
.PP
\fBwimlib-imagex export\fR \fISWM_PART_1\fR --ref="\fISWM_GLOB\fR" all \fIOUT_WIMFILE\fR
.RE
.SH SEE ALSO
.BR wimlib-imagex (1)
.BR wimlib-imagex-export (1)
