#!/bin/bash
#
# This script prepares a Windows binary distribution of wimlib on Linux using
# MinGW-w64.  The desired architecture must be passed as the first argument.

set -e

if [ ! -e src/wim.c ]; then
	echo "This script must be run from the toplevel directory" 1>&2
	exit 1
fi

if [ $# -lt 1 ]; then
	echo "Usage: $0 i686|x86_64 [EXTRA_CONFIGURE_ARG]..." 1>&2
	exit 1
fi

ARCH="$1"
shift

case "$ARCH" in
i686|x86_64)
	;;
*)
	echo "ERROR: ARCH must be i686 or x86_64" 1>&2
	exit 1
	;;
esac

VERSION=$(tools/get-version-number)
DESTDIR=wimlib-${VERSION}-windows-${ARCH}-bin
ZIPFILE=wimlib-${VERSION}-windows-${ARCH}-bin.zip
MAKE="make -j $(grep -c processor /proc/cpuinfo)"

# Compile wimlib

if ! [ -e config.log ] ||
	! grep -q "./configure --host=${ARCH}-w64-mingw32" config.log || \
	! grep -q "configure: exit 0" config.log || \
	[ $# -gt 0 ]
then
	# Note: putting -static-libgcc in CC is a workaround for libtool
	# stripping it:
	# http://www.gnu.org/software/libtool/manual/libtool.html#Stripped-link-flags
	./configure --host=${ARCH}-w64-mingw32 --disable-static		\
		CC="${ARCH}-w64-mingw32-gcc -static-libgcc" "$@"
	$MAKE clean
fi
$MAKE

# Create empty destination directory

rm -rf $DESTDIR
mkdir $DESTDIR

# Install binaries

cp .libs/*.{dll,exe} $DESTDIR
${ARCH}-w64-mingw32-strip $DESTDIR/*.{dll,exe}

# Install text files

cp NEWS README* COPYING* $DESTDIR

sed -n '/^#/q; s/^[\/\* ]*//; p' src/divsufsort.c > $DESTDIR/COPYING.libdivsufsort-lite
if ! grep -q 'Copyright' $DESTDIR/COPYING.libdivsufsort-lite; then
	echo "ERROR: failed to extract libdivsufsort-lite license text" 1>&2
	exit 1
fi
(
	cd $DESTDIR
	for fil in NEWS README* COPYING*; do
		sed < $fil > ${fil}.txt -e 's/$/\r/g'
		rm $fil
	done
)


# Install man pages

mkdir $DESTDIR/doc

function gen_pdf_from_man_page() {
	local manbase=$1
	local pdf=${DESTDIR}/doc/${manbase}.pdf

	echo "Generating $pdf"

	MANPATH="./doc" man -t $manbase | ps2pdf - $pdf
}

for fil in ./doc/man1/wim*.1; do
	manbase=`basename $fil`
	cmd=${manbase%.1}
	case $cmd in
	wimlib-imagex|wimmount|wimmountrw|wimunmount)
		continue
		;;
	esac

	gen_pdf_from_man_page $cmd

	sed 's/$/\r/g' > ${DESTDIR}/${cmd}.cmd <<- EOF
		@echo off
		"%~dp0\\wimlib-imagex" ${cmd#wim} %*
	EOF
	chmod +x ${DESTDIR}/${cmd}.cmd
done

gen_pdf_from_man_page wimlib-imagex

# Install development files

mkdir $DESTDIR/devel
cp .libs/libwim.dll.a $DESTDIR/devel/libwim.lib
cp include/wimlib.h $DESTDIR/devel/

# Generate ZIP file

rm -f $ZIPFILE
(
	dir=$PWD
	cd $DESTDIR
	7z -mx9 a "$dir/$ZIPFILE" .
)
