#!/bin/bash

oldver='1\.8\.3'
oldmonth=November
oldyear=2015

newmajor=1
newminor=9
newpatch=0
newmonth=January
newyear=2016


newver="${newmajor}.${newminor}.${newpatch}"
pat='This is wimlib version [^[:space:]]\+ ([^[:space:]]\+ [^[:space:]]\+)'
sed -i "s/$pat/This is wimlib version $newver ($newmonth $newyear)/" README

sed -i "s/$oldver/$newver/" configure.ac

sed -i -e 's/\(#define WIMLIB_MAJOR_VERSION[[:space:]]\+\)[[:digit:]]\+/\1'$newmajor'/' \
       -e 's/\(#define WIMLIB_MINOR_VERSION[[:space:]]\+\)[[:digit:]]\+/\1'$newminor'/' \
       -e 's/\(#define WIMLIB_PATCH_VERSION[[:space:]]\+\)[[:digit:]]\+/\1'$newpatch'/' \
       -e 's/\(the library interface of wimlib \)'$oldver'/\1'$newver'/' \
	  include/wimlib.h

sed -i -e "1s/$oldmonth $oldyear/$newmonth $newyear/;1s/wimlib $oldver/wimlib $newver/"	\
	  doc/man[1-9]/*.[1-9]

sed -i "s/pkgver=$oldver/pkgver=$newver/" archlinux/PKGBUILD

sed -i "1i\\
wimlib ($newver-1) unstable; urgency=low\\
\\
  * Update to v$newver\\
\\
 -- Eric Biggers <ebiggers3@gmail.com>  $(date -R)\\
" debian/changelog

sed -i 's/\(Version:[[:space:]]*\)[^[:space:]]\+/\1'"$newver"'/' \
		rpm/*.spec
